name: deals
favicon: null
layout_spectrum: 0.5710825608111918
typography_spectrum: 0.3210452061612159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6130833744537085
  lightness: 0.9530801540240645
  saturation: 0.7875849967822433
  rhythmicContrast: 0.7588908546604216
purpose: []
